[project]
name = "scenariocompass"
description = "Validation and analysis of integrated-assessment scenarios"
authors = [
    {name = "Daniel Huppmann", email = "huppmann@iiasa.ac.at"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11, <3.15"
dependencies = [
    "nomenclature-iamc (>=0.29.6)",
    "pyam-iamc (>=3.3.0)",
    "pandas (>=2.1.1)",
]
dynamic = ["version"]

[tool.poetry]
packages = [{include = "scenariocompass"}]
requires-poetry = ">=2.0,<3.0"
version = "0.0.0"

[project.urls]
homepage = "https://scenariocompass.org"
repository = "https://github.com/IAMconsortium/scenariocompass"

[tool.poetry.group.dev.dependencies]
ruff = "^0.15.0"

[tool.poetry.group.test.dependencies]
pytest = "^9.0.2"

[tool.poetry.group.docs.dependencies]
sphinx = ">=9.0.0,<9.1.0"
numpydoc = "^1.10.0"
sphinx-click = "^6.2.0"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.7.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
bump = true
enable = true
style = "pep440"
vcs = "git"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "poetry-dynamic-versioning>=1.7,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
